### ISSUE TITLE
Swarm mode - parse env var of bunkerized-nginx service and generate site configs

### ISSUE THREAD

**Issue by Crazy3lf** [bunkerity/bunkerized-nginx#107]
Hi, I was trying to host a static folder on `static.website.com` and a backend server on `app.website.com`.
The `docker-compose.yml` look something like this:
```yml
version: '3.8'

services:

  autoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /shared/confs:/etc/nginx
      - /shared/letsencrypt:/etc/letsencrypt
      - /shared/acme-challenge:/acme-challenge
    environment:
      - SWARM_MODE=yes
      - API_URI=/ChangeMeToSomethingHardToGuess
    networks:
      - net_config
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  nginx:
    image: bunkerity/bunkerized-nginx
    ports:
      - published: 80
        target: 8080
        mode: host
        protocol: tcp
      - published: 443
        target: 8443
        mode: host
        protocol: tcp
    volumes:
      - /shared/confs:/etc/nginx:ro
      - /shared/letsencrypt:/etc/letsencrypt:ro
      - /shared/acme-challenge:/acme-challenge:ro
      - /shared/www:/www:ro
    environment:
      - SWARM_MODE=yes
      - USE_API=yes
      - API_URI=/ChangeMeToSomethingHardToGuess
      - MULTISITE=yes
      - SERVER_NAME=static.website.com
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
    networks:
      - net_config
      - net_services
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - "bunkerized-nginx.AUTOCONF"

  app:
    image: phpmyadmin:apache
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://app.website.com
    networks:
      - net_services
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - "bunkerized-nginx.SERVER_NAME=app.website.com"
        - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
        - "bunkerized-nginx.REVERSE_PROXY_URL=/"
        - "bunkerized-nginx.REVERSE_PROXY_HOST=http://app"

networks:
  net_config:
    driver: overlay
  net_services:
    driver: overlay  
```
Note: I had custom server config for both site already in confs directory: `/shared/confs/static.website.com/frontend.conf` and `/shared/confs/app.website.com/backend.conf`.
When I start the stack, the logs show this:
```
[*] Starting bunkerized-nginx ...                                                                                                           
[*] Configuring bunkerized-nginx ...                                                                                                        
[*] Updating clamav (in background) ...                                                                                                     
[*] Successfully started temp nginx                                                                                                         
[*] Waiting until config has been generated ...                                                                                             
[*] Running nginx ...                                                                                                                       
nginx: [emerg] open() "/etc/nginx/app.test02.rgcredsys.xyz/server.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:113  
[!] nginx failed to start                                                                                                                   
[*] Running fail2ban ...                                                                                                                    
[*] bunkerized-nginx stopped                                                                                                                
[*] Starting bunkerized-nginx ...                                                                                                           
[*] Configuring bunkerized-nginx ...                                                                                                        
[*] Updating clamav (in background) ...                                                                                                     
[*] Successfully started temp nginx                                                                                                         
[*] Waiting until config has been generated ...                                                                                             
[*] Running nginx ...                                                                                                                       
nginx: [emerg] open() "/etc/nginx/static.website.com/server.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:113  
[!] nginx failed to start                                                                                                                   
```

I check the server conf directory and found that only `/shared/confs/app.website.com/` is populated with generated config files. but the `/shared/confs/static.website.com/` is not.  
I found [this line](https://github.com/bunkerity/bunkerized-nginx/blob/c5c5fb17b529941c11558a232bb70b426606e62c/entrypoint/entrypoint.sh#L72) that stop the generation of configs for when `MULTISITE=yes`. So is this the intended behavior?

**Comment by bunkerity** [comment]
Hello @Crazy3lf,

This is a use case we didn't think of when running in Swarm mode. The philosophy is to let the autoconf generating all the config files so yes this is the intended behavior. To fix this, the autoconf server needs to parse the environment variables of the bunkerized-nginx service when it's up and generate the configs. Let's add it to the TODO list, thanks for reporting this.

A possible workaround until this is fixed is to create a "dummy" service like this : 
```yaml
  nginx:
    ...
    environment:
      ...
      - SERVER_NAME= # keep it blank
      ...

  front:
    image: busybox
    command: sleep infinity
    deploy:
      replicas: 1
      placement:
        constraints:cat
          - "node.role==worker"
      labels:
        - "bunkerized-nginx.SERVER_NAME=front.website.com"
```

Please note if you want to add custom configuration files at server context, you need to use the */server-confs* volume (more info [here](https://github.com/bunkerity/bunkerized-nginx#include-custom-configurations)).
