### ISSUE TITLE
Autoconfigure it's not working properly

### ISSUE THREAD

**Issue by JustDevZero** [bunkerity/bunkerized-nginx#109]
I think I've got a weird bug or I'm missing something, I 've got two docker-compose files (for swarm), one is this:

```

version: '3.7'

services:

  django:
    #container_name: django
    volumes:
      - virtualenv_django:/home/django/virtualenv
      - /dev/shm:/dev/shm
      - /dev/shm:/tmp
      - ../logs:/home/black_pearl/logs
      - ../run:/run
      - ../static:/static
      - ../media:/media
      - ../dumps:/dumps
    image: 127.0.0.1:5000/django:master
    labels:
      - "bunkerized-nginx.SERVER_NAME=django.mydomain.com"
      - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=http://django:8000"

    build:
      context: ../code
      args:
        - INSTALLED_CUSTOM_REPOS=git+ssh://git@github.com/AndromedaSolutions/cms_lifexperiences.git
        - DJANGO_LOGS_DIR=/home/black_pearl/logs
      dockerfile: ../dockerfiles/djangocms.Dockerfile
    env_file:
      - ../environment_files/django.env
    depends_on:
      - database_django
    networks:
      - private-grp-net
      - net_services
    restart: unless-stopped

  database_cdjango:
    #container_name: database_django
    image: postgres:13.2-alpine
    env_file:
      - ../environment_files/django.env
    #command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - postgres_django:/var/lib/postgres:rw
      - postgresql_django_data:/var/lib/postgresql/data
      - ../dumps:/dumps
    networks:
      - private-grp-net
    restart: unless-stopped

volumes:
  virtualenv_django:
  postgres_django:
  postgresql_django_data:

networks:
  net_services:
    external: true
  private-grp-net:
    external: false



```

And the one for nginx:

```
version: '3.7'

services:

  autoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../shared/confs:/etc/nginx
      - ../shared/letsencrypt:/etc/letsencrypt
      - ../shared/acme-challenge:/acme-challenge
    environment:
      - SWARM_MODE=yes
      - API_URI=/NginxApiAutoConfV2
    networks:
      - net_config
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"


  nginx:
    image: bunkerity/bunkerized-nginx
    ports:
      - published: 80
        target: 8080
        mode: host
        protocol: tcp
      - published: 443
        target: 8443
        mode: host
        protocol: tcp
    volumes:
      - ../shared/confs:/etc/nginx
      - ../shared/letsencrypt:/etc/letsencrypt:ro
      - ../shared/acme-challenge:/acme-challenge:ro
      - ../shared/www:/www:ro
      - ../shared/http-confs:/http-confs
      - ../media:/media
      - ../static:/static:ro
    environment:
      - SWARM_MODE=yes
      - USE_API=yes
      - API_URI=/NginxApiAutoConfV2
      - MULTISITE=yes
      - SERVER_NAME=
      - AUTO_LETS_ENCRYPT=no
      - REDIRECT_HTTP_TO_HTTPS=no
      - DISABLE_DEFAULT_SERVER=yes
    networks:
      - net_config
      - net_services
    deploy:
      mode: global
      #placement:
        #constraints:
          #- "node.role==worker"
      labels:
        - "bunkerized-nginx.AUTOCONF"


networks:
  net_config:
    external: true
  net_services:
    external: true

```

But somehow, the autoconfigurer is not detecting properly when a new "django" is spinned up.

I am missing something?

Thanks!

**Comment by bunkerity** [comment]
Hi @JustDevZero,

Since you are running the autoconf in Swarm mode, you should set the labels for the django service under the deploy directive : 

```yaml
deploy:
  labels:
    - "bunkerized-nginx.SERVER_NAME=django.mydomain.com"
    - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
    - "bunkerized-nginx.REVERSE_PROXY_URL=/"
    - "bunkerized-nginx.REVERSE_PROXY_HOST=http://django:8000"
```

You have a compose example [here](https://github.com/bunkerity/bunkerized-nginx/blob/master/examples/swarm/stack.yml).
