### ISSUE TITLE
[BUG] Problem with avec autoconf, multisite and php site

### ISSUE THREAD

**Issue by Sorrow81** [bunkerity/bunkerized-nginx#135]
**Description**
Hello,

When I enable autoconf and start two services with a docker compose, the PHP service always returns a 404 error. After checking the files are available on the container. On the other hand if I go on the container of php:fpm that I make a curl on the port 9000 I obtain :
```
# curl 127.0.0.1:9000
curl: (56) Recv failure: Connection reset by peer
```

**How to reproduce**
Windows 10

```
/www
├── modsec-crs-confs
├── portfolio
│   └── index.html
│   └── docker-compose.yml
│   └── ...
├── strux
│   └── api
│   │   └── package.json
│   │   └── ...
│   └── client
│   │   └── package.json
│   │   └── Dockerfile.dev
│   │   └── ...
│   └── docker-compose.dev.yml
└── docker-compose.yml
```

```yml
version: '3'

services:

  www:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - autoconf:/etc/nginx
      - ./modsec-crs-confs:/modsec-crs-confs:ro # custom Core Rule Set confs to add Nextcloud exclusions
    environment:
      - SERVER_NAME=                                              # must be left blank if you don't want to setup "static" conf
      - MULTISITE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - LIMIT_REQ_RATE=5r/s
      - LIMIT_REQ_BURST=10
      - ALLOWED_METHODS=GET|POST|HEAD|DELETE|PUT
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - mynet

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autoconf:/etc/nginx
    depends_on:
      - www

volumes:
  autoconf:

networks:
  mynet:
    name: mynetname
 ```
 
 ```yml
version: '3'

services:

  api:
    image: strapi/strapi:3.6.2-alpine
    networks:
      mynet:
        aliases:
          - strux
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./api:/srv/app
    labels:
      - "bunkerized-nginx.SERVER_NAME=api.strux.local"            # replace with your domain
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=http://api:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    networks:
      mynet:
        aliases:
          - strux
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  client:
    build: 
        context: client
        dockerfile: Dockerfile.dev
    networks:
      mynet:
        aliases:
          - strux
    restart: always
    labels:
      - "bunkerized-nginx.SERVER_NAME=strux.local"            # replace with your domain
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=http://client:3000"
    depends_on:
      - api

networks:
  mynet:
    external:
      name: mynetname
 ```
 
  ```yml
version: '3'

services:

  www:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - autoconf:/etc/nginx
      - ./modsec-crs-confs:/modsec-crs-confs:ro # custom Core Rule Set confs to add Nextcloud exclusions
    environment:
      - SERVER_NAME=                                              # must be left blank if you don't want to setup "static" conf
      - MULTISITE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - LIMIT_REQ_RATE=5r/s
      - LIMIT_REQ_BURST=10
      - ALLOWED_METHODS=GET|POST|HEAD|DELETE|PUT
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - mynet

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autoconf:/etc/nginx
    depends_on:
      - www

volumes:
  autoconf:

networks:
  mynet:
    name: mynetname
 ```

```bash
 Sorrow@SW-ACER  D:\www  docker-compose up -d
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "mynetname" with the default driver
Creating network "www_default" with the default driver
Creating volume "www_autoconf" with default driver
Creating www_www_1 ... done
Creating www_myautoconf_1 ... done
 Sorrow@SW-ACER  D:\www  docker-compose -f .\portfolio\docker-compose.yml up -d
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating portfolio_portfolio_1 ... done
 Sorrow@SW-ACER  D:\www  docker-compose -f .\strux\docker-compose.dev.yml up -d
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating strux_postgres_1 ... done
Creating strux_api_1      ... done
Creating strux_client_1   ... done
```

![image](https://user-images.githubusercontent.com/43729314/118563976-c805ac80-b76f-11eb-89bc-58dea695af44.png)
![image](https://user-images.githubusercontent.com/43729314/118563994-d227ab00-b76f-11eb-8f6d-4a7a4f56e0a5.png)
![image](https://user-images.githubusercontent.com/43729314/118564032-e1a6f400-b76f-11eb-84ca-648e1b87fd47.png)

**Logs**
![image](https://user-images.githubusercontent.com/43729314/118564222-3a768c80-b770-11eb-857a-7cc787801cab.png)
[www_www_1.log](https://github.com/bunkerity/bunkerized-nginx/files/6497282/www_www_1.log)
[portfolio_portfolio_1.log](https://github.com/bunkerity/bunkerized-nginx/files/6497199/portfolio_portfolio_1.log)
[www_myautoconf_1.log](https://github.com/bunkerity/bunkerized-nginx/files/6497200/www_myautoconf_1.log)

**Comment by bunkerity** [comment]
Hello @Sorrow81,

Here is my feedback : 
- You can't do a curl on port 9000 because it's a FastCGI service, not HTTP
- You're using the same network alias "strux" for all of your services, each service should have its own unique alias (e.g. : api for api, client for client, ...)
- The compose file for portfolio is missing so I can't check the variables, can you share it ?

**Comment by Sorrow81** [comment]
Hi @bunkerity,

Sorry, it was a bit late when I sent my message and I put twice the same docker-compose.

I have taken your remarks into consideration but I still have the same error.

```yaml
# D:\www\docker-compose.yml

version: '3'

services:

  www:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - autoconf:/etc/nginx
      - ./modsec-crs-confs:/modsec-crs-confs:ro # custom Core Rule Set confs to add Nextcloud exclusions
    environment:
      - SERVER_NAME=                                              # must be left blank if you don't want to setup "static" conf
      - MULTISITE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - LIMIT_REQ_RATE=5r/s
      - LIMIT_REQ_BURST=10
      - ALLOWED_METHODS=GET|POST|HEAD|DELETE|PUT
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - mynet

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autoconf:/etc/nginx
    depends_on:
      - www

volumes:
  autoconf:

networks:
  mynet:
    name: mynetname
```

```yaml
# D:\www\portfolio\docker-compose.yml

version: '3'

services:

  portfolio:
    image: php:fpm
    networks:
     mynet:
       aliases:
         - portfolio
    restart: always
    volumes:
      - D:\www\portfolio:/app
    labels:
      - "bunkerized-nginx.SERVER_NAME=portfolio.local"            # replace with your domain
      - "bunkerized-nginx.REMOTE_PHP=portfolio"
      - "bunkerized-nginx.REMOTE_PHP_PATH=/app"

networks:
  mynet:
    external:
      name: mynetname
```

```yaml
# D:\www\strux\docker-compose.dev.yml

version: '3'

services:

  api:
    image: strapi/strapi:3.6.2-alpine
    networks:
     mynet:
       aliases:
         - api
    restart: always
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./api:/srv/app
    labels:
      - "bunkerized-nginx.SERVER_NAME=api.strux.local"            # replace with your domain
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=http://api:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    networks:
     mynet:
       aliases:
         - postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./postgres:/var/lib/postgresql/data
      
  client:
    build: 
        context: client
        dockerfile: Dockerfile.dev
    networks:
     mynet:
       aliases:
         - client
    restart: always
    labels:
      - "bunkerized-nginx.SERVER_NAME=strux.local"            # replace with your domain
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=http://client:3000"
    depends_on:
      - api

networks:
  mynet:
    external:
      name: mynetname
```

When i look in container www_www_1 in /etc/nginx/portfolio.local/nginx.env i see this :

```
REMOTE_PHP=portfolio
REMOTE_PHP_PATH=/app
REMOVE_HEADERS='Server X-Powered-By X-AspNet-Version X-AspNetMvc-Version'
ROOT_FOLDER=/www/portfolio.local
ROOT_SITE_SUBFOLDER=
```

I tried to change the docker-compose with this but it did not work:
```yaml
# D:\www\portfolio\docker-compose.yml
[...]
    volumes:
      - D:\www\portfolio:/var/www/portfolio.local
    labels:
      - "bunkerized-nginx.SERVER_NAME=portfolio.local"            # replace with your domain
      - "bunkerized-nginx.REMOTE_PHP=portfolio"
      - "bunkerized-nginx.REMOTE_PHP_PATH=/var/www/portfolio.local"
[...]
```

**Comment by bunkerity** [comment]
Hi @Sorrow81,

Another thing that comes to my mind : 
- The web files are not mounted on the bunkerized-nginx container
- You're using multisite, the directory on the host should follow a specific structure (e.g. : putting files for each site in a subdirectory named the same as the value of SERVER_NAME)

More info : [quickstart guide / multisite](https://github.com/bunkerity/bunkerized-nginx#multisite) and [multisite-basic example](https://github.com/bunkerity/bunkerized-nginx/blob/master/examples/multisite-basic/docker-compose.yml).

**Comment by Sorrow81** [comment]
Hi thanks for your reply, i modify little bit my docker-compose and it's work.

But why is needed for portfolio to rename folder to portfolio.local, for Strux is work perfectly ? Because is PHP service ? 

```yaml
# D:\www\docker-compose.yml

version: '3'

services:

  www:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - .:/www:ro
      - autoconf:/etc/nginx
      - ./modsec-crs-confs:/modsec-crs-confs:ro # custom Core Rule Set confs to add Nextcloud exclusions
    environment:
      - SERVER_NAME=                                              # must be left blank if you don't want to setup "static" conf
      - MULTISITE=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - LIMIT_REQ_RATE=5r/s
      - LIMIT_REQ_BURST=10
      - ALLOWED_METHODS=GET|POST|HEAD|DELETE|PUT
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - mynet

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autoconf:/etc/nginx
    depends_on:
      - www

volumes:
  autoconf:

networks:
  mynet:
    name: mynetname
```
 
 ```yaml
 # D:\www\portfolio\docker-compose.yml

version: '3'

services:

  portfolio:
    image: php:fpm
    networks:
     mynet:
       aliases:
         - portfolio
    restart: always
    volumes:
      - D:\www\portfolio.local:/app
    labels:
      - "bunkerized-nginx.SERVER_NAME=portfolio.local"            # replace with your domain
      - "bunkerized-nginx.REMOTE_PHP=portfolio"
      - "bunkerized-nginx.REMOTE_PHP_PATH=/app"

networks:
  mynet:
    external:
      name: mynetname
```

And it's possible to set ALLOWED_METHOD only on specific service (like API in my case) ?

In any case, thanks to you I managed to make multisite with autoconf 👍

**Comment by bunkerity** [comment]
You're right, your API is served through "reverse proxy" it means nginx doesn't need to have access to the web files.

Regarding the `ALLOWED_METHODS`, yes you can remove it from environment variables and add it as a label to the api service and it will be applied only to that service : 
```yaml
  api:
    labels:
      - "bunkerized-nginx.ALLOWED_METHODS=..."
```

Please note that you will need to destroy/recreate the service so autoconf can get the new labels.

Closing this as it seems to be resolved ! 👍
