### ISSUE TITLE
getting 403 error

### ISSUE THREAD

**Issue by peterkimzz** [bunkerity/bunkerized-nginx#14]
I'd like to set custom nginx block `upstream` for load balancing and app version rolling update, but nginx throws error below. 

`nginx: [emerg] "upstream" directive is not allowed here in /server-confs/default.conf:1`

Here are my codes.

**docker-compose.yml**
```yml
version: "3.8"

services:
  nginx:
    image: bunkerity/bunkerized-nginx
    volumes:
      - ./nginx/config:/server-confs
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
    environment:
      - SERVER_NAME=example.com
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes

  blue:
    build:
      context: app

  green:
    build:
      context: app

```

**default.conf**
```conf
upstream proxy {
    server blue:3000;
    server green:3000;
}

proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

location / {
    proxy_pass http://proxy;
}
```
