### ISSUE TITLE
Link open graph metadata preview doesn't work when paste website link

### ISSUE THREAD

**Issue by peterkimzz** [bunkerity/bunkerized-nginx#17]
![image](https://user-images.githubusercontent.com/20244536/97395523-7c50fa00-1928-11eb-9da4-ef38bb31349d.png)

As you can see when I paste link in Slack chat, Google open graph metadata preview works well, but live demo link and also my website don't. 

I wanted to see nginx log when I pasted link in Slack chat, but I couldn't see any logging.

Access to my website using a browser is working good, and there is no problem with my open graph HTML tags. (HTTP redirect status code also looks good)

All of 3rd party security service are off like this.

Same reason I tried to submit my `/sitemap.xml` file to any search engine except Google, they doesn't read the file.

**docker-compose.yml**

```yml
version: "3.8"

services:
  myreverse:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/http-configs:/http-confs
      - ./nginx/server-configs:/server-confs
    environment:
      - SERVER_NAME=www.example.com
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - X_FRAME_OPTIONS=SAMEORIGIN
      - USE_DNSBL=no
      - USE_FAIL2BAN=no
      - USE_MODSECURITY=no
      - USE_MODSECURITY_CRS=no
      - USE_CLAMAV_UPLOAD=no
      - USE_CLAMAV_SCAN=no
      - CLAMAV_SCAN_REMOVE=no
      - BLOCK_USER_AGENT=no
      - BLOCK_PROXIES=no
      - BLOCK_ABUSERS=no
```

**Comment by bunkerity** [comment]
Hello @peterkimzz can you try the new 1.1.0 version ? The logging bug should now be fixed in this version. Please note that nginx now listens on ports 8080 for HTTP and 8443 for HTTPS. Then try again to see if we have any logs ?

**Comment by peterkimzz** [comment]
Hi @bunkerity.

I used 1.1.0 version, still got same result. 
Looks all of crawler are blocked.

I think the reason why no any log is that some security tool or rule block ONLY for the crawlers before requesting to nginx.

**nginx log**  (still using curl and browser work)

```
myreverse_1  | [*] Running nginx ...
myreverse_1  | ==> /var/log/access.log <==
myreverse_1  | 
myreverse_1  | ==> /var/log/error.log <==
myreverse_1  | 
myreverse_1  | ==> /var/log/access.log <==
myreverse_1  | 211.176.129.xx - - [29/Oct/2020:02:02:14 +0000] "HEAD / HTTP/1.1" 301 0 "-" "curl/7.64.1"
myreverse_1  | 211.176.129.xx - - [29/Oct/2020:02:06:40 +0000] "GET / HTTP/2.0" 200 11357 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Whale/2.8.107.17 Safari/537.36"
```

**docker-compose.yml (adapted by v1.1.0)**

```
version: "3.8"

services:
  myreverse:
    image: bunkerity/bunkerized-nginx:1.1.0
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/http-configs:/http-confs
      - ./nginx/server-configs:/server-confs
    environment:
      - HEADER_SERVER=no
      - SERVER_NAME=www.example.com
      - SERVE_FILES=no
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - PROXY_REAL_IP=yes
      - USE_DNSBL=no
      - USE_FAIL2BAN=no
      - USE_MODSECURITY=no
      - USE_MODSECURITY_CRS=no
      - USE_CLAMAV_UPLOAD=no
      - USE_CLAMAV_SCAN=no
      - CLAMAV_SCAN_REMOVE=no
      - BLOCK_USER_AGENT=no
      - BLOCK_TOR_EXIT_NODE=no
      - BLOCK_PROXIES=no
      - BLOCK_ABUSERS=no
      - USE_WHITELIST_IP=no
      - USE_WHITELIST_REVERSE=no
      - USE_BLACKLIST_IP=no
      - USE_BLACKLIST_REVERSE=no
      - USE_LIMIT_REQ=no

  app1:
    image: "${DOCKER_REGISTRY}:www"
    restart: always
    command: yarn start

 # ...
```
