### ISSUE TITLE
[BUG] REVERSE_PROXY_URL behaviour is different in version 1.3.0

### ISSUE THREAD

**Issue by HugooB** [bunkerity/bunkerized-nginx#181]
**Description**
I have `bunkerized-nginx` running as a reverse proxy in front of a Flask API running in a different Docker container. In version 1.2.8, this worked fine, but it no longer works in version 1.3.0. Traffic meant for `/api/v1/endpoint` is routed to `api/v1/`. 

**How to reproduce**
A working configuration is as follows:

```
nginx:
    container_name: my_nginx_container
    image: bunkerity/bunkerized-nginx:1.2.8
    restart: always
    depends_on:
      - api
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - SERVER_NAME=$SERVER_NAME
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_MODSECURITY=yes
      - USE_MODSECURITY_CRS=no
      - BLOCK_USER_AGENT=no
      - BAD_BEHAVIOR_THRESHOLD=30
      - BAD_BEHAVIOR_BAN_TIME=7200
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/api/v1/
      - REVERSE_PROXY_HOST=http://api:5000/api/v1/
```

However, when upgrading to the latest version by changing bunkerized-nginx to`image: bunkerity/bunkerized-nginx:1.3.0` this config no longer works and all traffic is routed towards `/api/v1` on the API container, no matter what endpoint you chose.

**Logs**
```
SERVER_NAME <redacted_ip> - - [01/Sep/2021:09:03:34 +0000] "GET /api/v1/endpoint HTTP/1.1" 200 21791 "-" "PostmanRuntime/7.28.4"
```

**Comment by fl0ppy-d1sk** [comment]
Hello @HugooB,

Can you try to replace `REVERSE_PROXY_HOST=http://api:5000/api/v1/` with `REVERSE_PROXY_HOST=http://api:5000` ?

**Comment by HugooB** [comment]
> Can you try to replace `REVERSE_PROXY_HOST=http://api:5000/api/v1/` with `REVERSE_PROXY_HOST=http://api:5000` ?
Hi @fl0ppy-d1sk and thanks for your reply! I tried that, did not make any difference. As far as I can see, something has changed regarding the handling of reverse proxy URLs in version 1.3.0.

**Comment by fl0ppy-d1sk** [comment]
Hello @HugooB,

Looks like I can't reproduce your issue. Here is a basic docker-compose file : 
```yaml
version: '3'
services:
  front:
    image: bunkerity/bunkerized-nginx:1.3.1
    ports:
      - 80:8080
    environment:
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_HOST=http://back
      - REVERSE_PROXY_URL=/api/v1/
  back:
    image: tutum/hello-world
```

Request sent to **http://localhost/api/v1/somewhere** is proxied to the **http://backend/api/v1/somewhere** : 
```log
front_1  | localhost 172.24.0.1 - - [13/Sep/2021:19:40:49 +0000] "GET /api/v1/somewhere HTTP/1.1" 200 490 "-" "legit"
back_1   | 172.24.0.3 - - [13/Sep/2021:19:40:49 +0000] "GET /api/v1/somewhere HTTP/1.1" 200 490 "-" "legit"
```

And request sent to **http://localhost/elsewhere** is not proxied : 
```log
front_1  | localhost 172.24.0.1 - - [13/Sep/2021:19:41:00 +0000] "GET /elsewhere HTTP/1.1" 404 528 "-" "legit"
```

Can you double check that you created a new container (and not a simple restart) after editing the `REVERSE_PROXY_HOST` variable ?

**Comment by HugooB** [comment]
It seems that the problem was all about the final backslash.. With this configuration, everything worked smoothly again:

```
nginx:
    container_name: my_nginx_container
    image: bunkerity/bunkerized-nginx:1.3.1
    restart: always
    depends_on:
      - api
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - SERVER_NAME=$SERVER_NAME
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_MODSECURITY=yes
      - USE_MODSECURITY_CRS=no
      - BLOCK_USER_AGENT=no
      - BAD_BEHAVIOR_THRESHOLD=30
      - BAD_BEHAVIOR_BAN_TIME=7200
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/api/v1/
      - REVERSE_PROXY_HOST=http://api:5000
```

Thanks!
