### ISSUE TITLE
403 code on DELETE method

### ISSUE THREAD

**Issue by apkrymov** [bunkerity/bunkerized-nginx#19]
Nginx used as the reverse-proxy to other application. 

I allow DELETE method by environment:
_ALLOWED_METHODS=GET|POST|PUT|DELETE_

But other applications don`t receive requests with DELETE method from Nginx, which always respond 403 to the browser. Another operation works correctly.

P.S I found root of the problem in mod_security. REQUEST-949-BLOCKING-EVALUATION.conf

**Comment by bunkerity** [comment]
Hello @apkrymov, did you resolve this issue ?

Just in case someone else has the same issue : you need to tweak the ModSecurity CRS settings to allow the methods (just like the [nextcloud example](https://github.com/bunkerity/bunkerized-nginx/tree/master/examples/nextcloud)).

docker-compose.yml example : 
```yaml
version: '3'
services:
  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./modsec-crs-confs:/modsec-crs-confs
    environment:
      - ALLOWED_METHODS=GET|POST|PUT|DELETE
```

content of modsec-csr-confs/methods.conf : 
```
SecAction \
 "id:900200,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.allowed_methods=GET POST PUT DELETE'"
```
