### ISSUE TITLE
[HELP] Can you help me to Bunkerized Pwndoc ?

### ISSUE THREAD

**Issue by Sorrow81** [bunkerity/bunkerized-nginx#220]
Hello, i want to bunkerized Pwndoc : https://github.com/pwndoc/pwndoc

Pwndoc is a website to manage pentest. Actually when i try to bunkerized this, i'm able to reach pwndoc when i specify port 8443 in url. My REDIRECT_HTTP_TO_HTTPS is working.

I tries many things without success.

I think [nginx.conf](https://github.com/pwndoc/pwndoc/blob/master/frontend/.docker/nginx.conf)  is my problems, but i can't solve it.

**How to reproduce**
Clone repository pwndoc
`git clone https://github.com/pwndoc/pwndoc.git pwndoc.sorrow.local`

Edit docker-compose.yml

`cd pwndoc.sorrow.local`
`nano docker-compose.yml`

```yaml
#/home/sorrow/vps/www/pwndoc.sorrow.local/docker-compose.yml
version: '3'
services:
  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - services-net

  pwndoc-backend:
    build: ./backend
    image: yeln4ts/pwndoc:backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks:
      services-net:
        aliases:
          - pwndoc-backend
    labels:
      - "bunkerized-nginx.SERVER_NAME=pwndocbackend.sorrow.local" # replace with your domain
      - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=https://pwndoc-backend:4242"
      - "bunkerized-nginx.USE_BAD_BEHAVIOR=no"
      - "bunkerized-nginx.REDIRECT_HTTP_TO_HTTPS=yes"

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      services-net:
        aliases:
          - pwndoc-frontend
    labels:
      - "bunkerized-nginx.SERVER_NAME=pwndocfrontend.sorrow.local" # replace with your domain
      - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
      - "bunkerized-nginx.REVERSE_PROXY_URL=/"
      - "bunkerized-nginx.REVERSE_PROXY_HOST=https://pwndoc-frontend:8443"
      - "bunkerized-nginx.USE_BAD_BEHAVIOR=no"
      - "bunkerized-nginx.REDIRECT_HTTP_TO_HTTPS=yes"

volumes:
  mongo-data:

networks:
  services-net:
    external:
      name: services-net
```

Create bunkerized autoconf

`cd ../..`
`nano docker-compose.yml`

```yaml
#/home/sorrow/vps/docker-compose.yml
version: '3'

services:

  mybunkerized:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      #- 443:8443
    volumes:
      #- ./certs:/etc/letsencrypt
      - ./www:/www:ro
      - bunkerized-vol:/etc/nginx
    environment:
      - SERVER_NAME=
      - MULTISITE=yes
      #- AUTO_LETS_ENCRYPT=yes
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - services-net

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes_from:
      - mybunkerized
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mybunkerized

volumes:
  bunkerized-vol:

networks:
  services-net:
    name: services-net
```

Run bunkerized and pwndoc

`docker-compose up -d`

`cd www/pwndoc.sorrow.local`

`docker-compose up --build`

If I comment mapping of port, i'm not able to reach Pwndoc. But with this, i'm able to reach service with ip and port, not only with SERVER_NAME.

Thank you to those who can help me.
