### ISSUE TITLE
Nginx cannot resolve the host, occasional 502 bad gateway

### ISSUE THREAD

**Issue by xn3cr0nx** [bunkerity/bunkerized-nginx#39]
Hey, thanks for you huge work here!

I'm facing an annoying behavior from nginx. I configured it as a simple reverse proxy passing traffic to my application (a ruby app). Sometimes the response is `502 Bad Gateway`, but refreshing the page the app is correctly served. It seems this happens with all new users. As far as I understood [here](https://github.com/docker/compose/issues/3412), this is due to nginx not able to resolve the host inside the docker network. 

Below you can fin my logs when this happens the show exactly how nginx is not able to resolve the host:
```
95.232.164.161 - - [28/Nov/2020:18:57:38 +0000] "GET / HTTP/2.0" 502 150 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"

==> /var/log/error.log <==
2020/11/28 18:57:38 [error] 987273#987273: *221 decidim could not be resolved (3: Host not found), client: 95.232.164.161, server: lombardia.amicidiazione.it, request: "GET / HTTP/2.0", host: "staging.amicidiazione.it"
```

Someone advised to specify the resolver in the http in order to make it resolve correctly, but is doesn't seem to work. I also tried to force an upstream binding the `http-confs` folder as you advised [here](https://github.com/bunkerity/bunkerized-nginx/issues/14#issuecomment-715145226), but I always get 502 because it says again it cannot resolve the host, but this time with the upstream name.

Do you know how this can be limited?

**Comment by bunkerity** [comment]
Hello @xn3cr0nx, can you try setting the `DNS_RESOLVERS` environment variable to **127.0.0.11** and tell me if that changes anything please ?

**Comment by bunkerity** [comment]
Can give us your docker-compose.yml file or commands so we can investigate on this bug ?

**Comment by xn3cr0nx** [comment]
thanks @bunkerity, it feels like `DNS_RESOLVERS` could have fixed it, I am not getting 502 anymore, but I need to monitor its behavior. 

In the following I paste the current docker-compose file (removing secrets and not interesting services like postgres and redis). [here](https://github.com/EntraInAzione/PartecipAzione) you can find the original file, but I edited it as follows due to staging testing.
```
version: '3.7'

x-env: &env production
x-decidim: &decidim 0.23.1
x-ruby: &ruby 
  RUBY_VERSION: 2.6.6

x-network: &network
  networks:
    decidim:

services:
  decidim:
    container_name: decidim
    hostname: decidim-host
    image: *pg-db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - decidim-gems:/usr/local/bundle:delegated
      - decidim-uploads://home/decidim/azione-decidim/public/uploads
      - decidim-config:/home/decidim/azione-decidim/config
    environment:
      PORT: 3000
      DATABASE_HOST: pg
      DATABASE_USERNAME: *pg-user
      DATABASE_NAME: *pg-db
      RAILS_ENV: *env
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres@pg:5432/azione-decidim_production
      RAILS_SERVE_STATIC_FILES: "true"
      SECRETKEY: secret
      SECRET_KEY_BASE: secret
      DECIDIM_VERSION: *decidim
      # RAILS_LOG_TO_STDOUT: true
      <<: [*ruby, *admin, *org, *smtp]
    depends_on:
      - pg
      - redis
      - nginx
    links:
      - pg
      - redis
    <<: *network
      
  nginx:
    image: bunkerity/bunkerized-nginx
    container_name: nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      AUTO_LETS_ENCRYPT: "yes" 
      REDIRECT_HTTP_TO_HTTPS: "yes"
      SERVER_NAME: lombardia.amicidiazione.it milano.amicidiazione.it staging.amicidiazione.it
      MULTISITE: "yes"
      DISABLE_DEFAULT_SERVER: "yes"
      ALLOWED_METHODS: "GET|POST|HEAD|OPTIONS|PUT|DELETE"
      WRITE_ACCESS: "yes"
      REFERRER_POLICY: "origin"
      USE_CLAMAV_UPLOAD: "no"
      USE_CLAMAV_SCAN: "no"
      CLAMAV_SCAN_REMOVE: "no"
      ADDITIONAL_MODULES: "ruby"
      USE_MODSECURITY_CRS: "no"
      USE_MODSECURITY: "no"
      DNS_RESOLVERS: "127.0.0.11"
    volumes:
      - nginx-letsencrypt:/etc/letsencrypt
      - ./server-confs:/server-confs
      - ./http-confs:/http-confs
    <<: *network 

volumes:
  pg:
  redis:
  decidim-gems:
  decidim-config:
  decidim-uploads:
  nginx-letsencrypt:

networks:
  decidim:
```
