### ISSUE TITLE
nginx fall down into container without error message

### ISSUE THREAD

**Issue by zakabluk** [bunkerity/bunkerized-nginx#43]
Nginx fall down into container without error message. Just in one moment my web application become not available.
```
image = "bunkerity/bunkerized-nginx:1.1.2"
```
my options
```
        "SERVE_FILES" = "no"
        "HTTP_PORT" = "80"
        "HTTPS_PORT" = "443"
        "USE_LIMIT_REQ" = "no"
        "LIMIT_REQ_BURST" = "1000"
        "USE_MODSECURITY" = "no"
        "USE_MODSECURITY_CRS" = "no"
        "AUTH_BASIC_LOCATION" = "sitewide"
        "REDIRECT_HTTP_TO_HTTPS" = "yes"
        "AUTO_LETS_ENCRYPT" = "yes"
        "DISABLE_DEFAULT_SERVER" = "yes"
        "USE_AUTH_BASIC" = "yes"
        "SERVER_NAME" = "my_sites"
        "AUTH_BASIC_USER" = "{{ auth_basic_user }}"
        "AUTH_BASIC_PASSWORD" =  "{{ auth_basic_password }}"
        "USE_DNSBL" = "no"
```

**Comment by souchprod** [comment]
Same, have to restart it almost 1x / day

**Comment by bunkerity** [comment]
@zakabluk  : 
It might be related to the fact that nginx is not running as root and can't bind to TCP/80 and TCP/443. I know you use the host networking but can you try the default bridge networking and tell me if that solves it ?
```yaml
version: '3'
services:
  www:
    image: bunkerity/bunkerized-nginx:1.1.2
    ports:
      - 80:8080
      - 443:8443
    environment:
      - ... your vars ...
```

@souchprod : 
Is there any info with docker(-compose) logs ? Can you share your compose file, bunkerized-nginx version, env vars, ... ? Don't forget to edit private data.
