### ISSUE TITLE
custom modsecurity conf by site when MULTISITE=yes doesn't work in dev branch

### ISSUE THREAD

**Issue by thelittlefireman** [bunkerity/bunkerized-nginx#52]
hi,
custom mod security by site doesn't work any more on Dev branch.

docker-compose
```yaml
version: '3.5'

services: 
  nginx_test:
    image: bunkerity/bunkerized-nginx:latest
    container_name: nginx_test
    restart: always
    network_mode: "host"
    ports:
      - 10080
      - 10443
    volumes:
      - ./nginx_test/www:/www
      - ./nginx_test/letsencrypt:/etc/letsencrypt
      - ./nginx_test/server-confs:/server-confs # custom nginx confs at server context to make Nextcloud working
      - ./nginx_test/modsec-crs-confs:/modsec-crs-confs # custom Core Rule Set confs to add Nextcloud exclusions
      - ./nginx_test/modsec-confs:/modsec-confs # disable some false positive
      - ./nginx_test/cache:/cache # blacklist geoip
      # /etc/nginx/fail2ban-ip.conf
      # Set timezone
      - "/etc/TZ:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - EMAIL_LETS_ENCRYPT=admin@mydomain
      - SERVER_NAME=syno.mydomain nextcloud.mydomain bitwarden.mydomain portainer.mydomain # replace with your domain
      - SERVE_FILES=yes #allow serving single file on wwww
      - HTTP_PORT=10080
      - HTTPS_PORT=10443
      - HTTP2=yes
      - HTTPS_PROTOCOLS=TLSv1.2 TLSv1.3
      
      - USE_GZIP=yes
      - GZIP_COMP_LEVEL=7
      - GZIP_MIN_LENGTH=20
      - USE_BRTOLI=yes
      - BROTLI_COMP_LEVEL=7
      - BROTLI_MIN_LENGTH=20
      
      - FAIL2BAN_STATUS_CODE=400|401|403|405|444 #remove 404 ==> need to test
      - PROXY_REAL_IP=yes
      - PROXY_REAL_IP_HEADER=X-Forwarded-For
      - PROXY_REAL_IP_RECURSIVE=on
      - PROXY_REAL_IP_FROM=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - USE_REVERSE_PROXY=yes
      
[...]
      
      - nextcloud.mydomain_REVERSE_PROXY_URL=/
      - nextcloud.mydomain_REVERSE_PROXY_HOST=http://localhost:32680/
      - nextcloud.mydomain_REVERSE_PROXY_WS=yes
      - nextcloud.mydomain_ALLOWED_METHODS=GET|POST|HEAD|PROPFIND|DELETE|PUT|MKCOL|MOVE|COPY|PROPPATCH|REPORT
      - nextcloud.mydomain_MAX_CLIENT_SIZE=0
      
[...]
      
      #TODO librephotos
      - USE_DNSBL=yes #check if mail.mydomain is not blocked ...
     #- DNSBL_LIST=bl.blocklist.de problems.dnsbl.sorbs.net sbl.spamhaus.org xbl.spamhaus.org
      - USE_MODSECURITY=yes
      - USE_MODSECURITY_CRS=yes
      - USE_CROWDSEC=yes
      - BLOCK_USER_AGENT=yes
      - BLOCK_TOR_EXIT_NODE=yes
      - BLOCK_PROXIES=yes
      - BLOCK_ABUSERS=yes
      - USE_WHITELIST_REVERSE=no # default is true TODO custom whitelist
      - USE_BLACKLIST_REVERSE=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      
      - USE_LIMIT_REQ=yes
      - LIMIT_REQ_RATE=40r/s
      - LIMIT_REQ_BURST=60
      - LIMIT_REQ_CACHE=50m
      - BLOCK_COUNTRY=cn ru
      - USE_CLAMAV_UPLOAD=yes
      - USE_CLAMAV_SCAN=yes
      - CLAMAV_SCAN_REMOVE=yes
      
      - USE_OPEN_FILE_CACHE=yes
      - OPEN_FILE_CACHE=max=1000 inactive=20s
      - OPEN_FILE_CACHE_ERRORS=on
      - OPEN_FILE_CACHE_MIN_USES=2
      - OPEN_FILE_CACHE_VALID=30s
```

/modsec-confs/nextcloud.mydomain/custom.conf

#45 
```
SecRuleEngine DetectionOnly

SecRequestBodyLimit 512107200

### TEMP FIX BEFORE CRS 3.4 !!! ###

# Fix for Nextcloud Desktop Client
SecRule REQUEST_METHOD "@streq PROPFIND" \
    "id:9003108,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    ver:'OWASP_CRS/3.3.0',\
    chain"
    SecRule REQUEST_FILENAME "@contains /remote.php/webdav" \
        "t:none,\
        ctl:ruleRemoveById=921110"
```

/modsec-crs-confs/nextcloud.mydomain/custom.conf
```
SecAction \
 "id:900130,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.crs_exclusions_nextcloud=1" # enable the nextcloud exclusion rules
  
SecAction \
 "id:900200,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.allowed_methods=GET HEAD POST PROPFIND DELETE PUT MKCOL MOVE COPY PROPPATCH REPORT'"

```

result : 

```
/etc/nginx/nextcloud.berlioz.me # cat modsecurity-rules.conf
# process rules with disruptive actions
SecRuleEngine On

# allow body checks
SecRequestBodyAccess On

# enable XML parsing
SecRule REQUEST_HEADERS:Content-Type "(?:application(?:/soap\+|/)|text/)xml" \
     "id:'200000',phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"

# enable JSON parsing
SecRule REQUEST_HEADERS:Content-Type "application/json" \
     "id:'200001',phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=JSON"

# maximum data size
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072

# reject requests if bigger than max data size
SecRequestBodyLimitAction Reject

# reject if we can't process the body
SecRule REQBODY_ERROR "!@eq 0" \
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

# be strict with multipart/form-data body
SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
"id:'200003',phase:2,t:none,log,deny,status:400, \
msg:'Multipart request body failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_MISSING_SEMICOLON}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IP %{MULTIPART_INVALID_PART}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
FL %{MULTIPART_FILE_LIMIT_EXCEEDED}'"
SecRule MULTIPART_UNMATCHED_BOUNDARY "@eq 1" \
    "id:'200004',phase:2,t:none,log,deny,msg:'Multipart parser detected a possible unmatched boundary.'"

# enable response body checks
SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml application/json
SecResponseBodyLimit 524288
SecResponseBodyLimitAction ProcessPartial

# log usefull stuff
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogType Serial
SecAuditLog /var/log/nginx/modsec_audit.log

# scan uploaded files with clamv
include /etc/nginx/nextcloud.berlioz.me/modsecurity-clamav.conf

# include OWASP CRS rules
include /etc/nginx/owasp-crs.conf
**### MISSING MODSECURITY LINE CUSTOM HERE ###**
include /etc/nginx/owasp-crs/*.conf

# include custom rules
```

Thanks
